### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by gbcox** [spr/Oggify#10]
A bit of advanced notice on this... Python 2 support is ending January, 2020 - and Fedora is taking steps to remove it from the distribution:  https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

Is it possible to migrate this app to Python 3?  If not, I'll have to remove it from Fedora when Python 2 support ends.

Thanks!

**Comment by spr** [comment]
I'll have to check to see if the dependencies are available in python3, but otherwise we should be able to migrate fairly easily.

**Comment by spr** [comment]
And, yep, it looks like mutagen supports 3.4+, so it's just a matter of me making the transition.

**Comment by gbcox** [comment]
Great, thanks!

**Comment by gbcox** [comment]
Hi... just a reminder that Fedora will remove Python2 from the distribution effective with F32, which will be approximately May, 2020 - and official support ends January 2020.  Here is the ticket:  https://bugzilla.redhat.com/show_bug.cgi?id=1738062

**Comment by spr** [comment]
Thanks for the reminder. Just got the unit tests passing in Python 3, going to work on real file testing next.

**Comment by gbcox** [comment]
Great news!  Very glad you're working on it.  As soon as it's ready, l'll get it in the repository.

**Comment by CAM-Gerlach** [comment]
@spr Just FYI, it is now marked for removal if it hasn't been removed already. Thanks.

**Comment by spr** [comment]
I've got a branch that solves the issue. The only additional thing is it needs a recent version of mutagen, but that should come with the python3 move anyways.

I still have to build the tar file though.

**Comment by spr** [comment]
[Release 2.2.0](https://github.com/spr/Oggify/releases/tag/2.2.0)

With that, I think Oggify is working fine with Python 3 (I tested specifically with 3.7, but it doesn't use anything that isn't in 3.4 and later).
